In [1]:
!pip install selenium
!pip install beautifulsoup4

Requirement already satisfied: selenium in ./opt/anaconda3/lib/python3.9/site-packages (4.2.0)
Requirement already satisfied: trio-websocket~=0.9 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (0.21.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in ./opt/anaconda3/lib/python3.9/site-packages (from selenium) (1.26.10)
Requirement already satisfied: idna in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: attrs>=19.2.0 in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: outcome in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: async-generator>=1.9 in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in ./opt/anaconda3/lib/python3.9/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: wsproto>=0.14 in ./opt/anaconda3/lib/python3.9/site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: cryptography>=1.3.4 in ./opt/anaconda3/lib/python3.9/site-packages (from urllib3[secure,socks]~=1.26->selenium) (37.0.4)
Requirement already satisfied: certifi in ./opt/anaconda3/lib/python3.9/site-packages (from urllib3[secure,socks]~=1.26->selenium) (2022.6.15)
Requirement already satisfied: pyOpenSSL>=0.14 in ./opt/anaconda3/lib/python3.9/site-packages (from urllib3[secure,socks]~=1.26->selenium) (22.0.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in ./opt/anaconda3/lib/python3.9/site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: cffi>=1.12 in ./opt/anaconda3/lib/python3.9/site-packages (from cryptography>=1.3.4->urllib3[secure,socks]~=1.26->selenium) (1.15.1)
Requirement already satisfied: pycparser in ./opt/anaconda3/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=1.3.4->urllib3[secure,socks]~=1.26->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in ./opt/anaconda3/lib/python3.9/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Requirement already satisfied: beautifulsoup4 in ./opt/anaconda3/lib/python3.9/site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in ./opt/anaconda3/lib/python3.9/site-packages (from beautifulsoup4) (2.3.1)

In [2]:
import selenium
from bs4 import BeautifulSoup
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.

In [4]:
driver= webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')
url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [5]:
name=[]
name_tag=driver.find_elements_by_xpath('/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr/td[2]')
for i in name_tag:
    name.append(i.text)
print(len(name)) 
print(name)

19
["Pinkfong Baby Shark - Kids' Songs & Stories", 'Luis Fonsi', 'Wiz Khalifa', 'Psy', 'Justin Bieber', 'Lady Gaga', 'HDCYT', 'Judson Laipply', 'RCA Records', 'Judson Laipply', 'CLARUSBARTEL72', 'Judson Laipply', 'Smosh', 'eggtea', 'mugenized', 'youtubedude', 'Nikesoccer', 'larfus', 'jawed']

In [6]:
uploader=[]
uploader_tag=driver.find_elements_by_xpath('/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr/td[3]')
for i in uploader_tag:
    uploader.append(i.text)
print(len(uploader)) 
print(uploader)

19
['7,046,700,000', '3,002,800,000', '2,894,000,000', '803,700,000', '245,400,000', '178,400,000', '128,900,000', '118,900,000', '92,600,000', '78,400,000', '76,600,000', '10,600,000', '4,300,000', '2,700,000', '3,400,000', '2,300,000', '255,000', '247,000', '1']

In [7]:
view=[]
view_tag=driver.find_elements_by_xpath('/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr/td[4]')
for i in view_tag:
    view.append(i.text)
print(len(view)) 
print(view)

19
['June 17, 2016', 'January 12, 2017', 'April 6, 2015', 'July 15, 2012', 'February 19, 2010', 'November 24, 2009', 'May 22, 2007', 'April 6, 2006', 'February 27, 2007', 'April 6, 2006', 'April 9, 2007', 'April 6, 2006', 'November 28, 2005', 'January 31, 2006', 'December 1, 2005', 'December 18, 2005', 'October 21, 2005', 'October 5, 2005', 'April 23, 2005']

In [8]:
date=[]
date_tag=driver.find_elements_by_xpath('/html/body/div[3]/div[3]/div[5]/div[1]/table[3]/tbody/tr/td[5]')
for i in date_tag:
    date.append(i.text)
print(len(date)) 
print(date)

19
['November 2, 2020', 'August 4, 2017', 'July 10, 2017', 'November 24, 2012', 'July 16, 2010', 'April 14, 2010', 'October 25, 2009', 'May 2, 2009', 'July 17, 2008', 'March 15, 2008', 'March 1, 2008', 'May 19, 2006', 'March 12, 2006', 'February 18, 2006', 'January 21, 2006', 'January 9, 2006', 'October 31, 2005', 'October 29, 2005', 'April 23, 2005']

In [9]:
df=pd.DataFrame({})
df['Video Name']=name
df['Uploader']=uploader
df['Views in Billions']=view
df['Upload Date']=date
df

,Video Name,Uploader,Views in Billions,Upload Date
0,Pinkfong Baby Shark - Kids' Songs & Stories,"7,046,700,000","June 17, 2016","November 2, 2020"
1,Luis Fonsi,"3,002,800,000","January 12, 2017","August 4, 2017"
2,Wiz Khalifa,"2,894,000,000","April 6, 2015","July 10, 2017"
3,Psy,"803,700,000","July 15, 2012","November 24, 2012"
4,Justin Bieber,"245,400,000","February 19, 2010","July 16, 2010"
5,Lady Gaga,"178,400,000","November 24, 2009","April 14, 2010"
6,HDCYT,"128,900,000","May 22, 2007","October 25, 2009"
7,Judson Laipply,"118,900,000","April 6, 2006","May 2, 2009"
8,RCA Records,"92,600,000","February 27, 2007","July 17, 2008"
9,Judson Laipply,"78,400,000","April 6, 2006","March 15, 2008"
10,CLARUSBARTEL72,"76,600,000","April 9, 2007","March 1, 2008"
11,Judson Laipply,"10,600,000","April 6, 2006","May 19, 2006"
12,Smosh,"4,300,000","November 28, 2005","March 12, 2006"
13,eggtea,"2,700,000","January 31, 2006","February 18, 2006"
14,mugenized,"3,400,000","December 1, 2005","January 21, 2006"
15,youtubedude,"2,300,000","December 18, 2005","January 9, 2006"
16,Nikesoccer,"255,000","October 21, 2005","October 31, 2005"
17,larfus,"247,000","October 5, 2005","October 29, 2005"
18,jawed,1,"April 23, 2005","April 23, 2005"

# Answer 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.

In [10]:
browser = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [11]:
browser.get('https://www.bcci.tv/')
browser.maximize_window()
time.sleep(5)

In [12]:
try:
    accept_button = browser.find_element_by_xpath("//button[@class='cookie__accept btn btn-primary']")
    accept_button.click()
except:
    pass

In [13]:
international_button = browser.find_element_by_xpath("//a[@href='https://www.bcci.tv/international/fixtures']")
international_button.click()

In [14]:
time.sleep(5)

In [15]:
fixture_cards = browser.find_elements_by_xpath("//div[@class='fixture-card-top']")
fixture = []
for i in fixture_cards:
    fixture.append(i.text.split('\n'))
fixture

[['INDIA TOUR OF ZIMBABWE ODI SERIES 2022', '18 AUG 2022', '12:45 PM IST'],
 ['INDIA TOUR OF ZIMBABWE ODI SERIES 2022', '20 AUG 2022', '12:45 PM IST'],
 ['INDIA TOUR OF ZIMBABWE ODI SERIES 2022', '22 AUG 2022', '12:45 PM IST'],
 ['ASIA CUP 2022', '28 AUG 2022', '7:30 PM IST'],
 ['ASIA CUP 2022', '31 AUG 2022', '7:30 PM IST'],
 ['AUSTRALIA TOUR OF INDIA T20 SERIES 2022', '20 SEP 2022', '7:30 PM IST'],
 ['AUSTRALIA TOUR OF INDIA T20 SERIES 2022', '23 SEP 2022', '7:30 PM IST'],
 ['AUSTRALIA TOUR OF INDIA T20 SERIES 2022', '25 SEP 2022', '7:30 PM IST']]

In [16]:
series = []
date = []
matchtime = []

for i in fixture:
    series.append(i[0])
    date.append(i[1])
    matchtime.append(i[2])

In [17]:
matches = browser.find_elements_by_xpath("//div[@class='fix-place ng-binding ng-scope']")
match=[]
for i in matches:
    match.append(i.text.split('\n'))

In [18]:
match

[['1st ODI - Harare Sports Club, Harare'],
 ['2nd ODI - Harare Sports Club, Harare'],
 ['3rd ODI - Harare Sports Club, Harare'],
 ['1st T20I - Dubai International Cricket Stadium, Dubai'],
 ['2nd T20I - Dubai International Cricket Stadium, Dubai'],
 ['1st T20I - Punjab Cricket Association IS Bindra Stadium, Mohali'],
 ['2nd T20I - Vidarbha Cricket Association Stadium, Nagpur'],
 ['3rd T20I - Rajiv Gandhi International Stadium, Hyderabad']]

In [19]:
title=[]
location=[]
for i in match:
    if str(i).find('-')!=-1:
        title.append(str(i).split('-')[0])
        location.append(str(i).split('-')[1])
    else:
        title.append('-')
        location.append(i)

In [20]:
for j in range(0,len(title)):
    title[j]=title[j].replace('[','')

In [21]:
bcci = pd.DataFrame()
bcci['Match Title'] = title
bcci['Series'] = series
bcci['Place'] = location
bcci['Date'] = date
bcci['Time'] = matchtime
bcci

,Match Title,Series,Place,Date,Time
0,'1st ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare']",18 AUG 2022,12:45 PM IST
1,'2nd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare']",20 AUG 2022,12:45 PM IST
2,'3rd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club, Harare']",22 AUG 2022,12:45 PM IST
3,'1st T20I,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai']",28 AUG 2022,7:30 PM IST
4,'2nd T20I,ASIA CUP 2022,"Dubai International Cricket Stadium, Dubai']",31 AUG 2022,7:30 PM IST
5,'1st T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Punjab Cricket Association IS Bindra Stadium,...",20 SEP 2022,7:30 PM IST
6,'2nd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Vidarbha Cricket Association Stadium, Nagpur']",23 SEP 2022,7:30 PM IST
7,'3rd T20I,AUSTRALIA TOUR OF INDIA T20 SERIES 2022,"Rajiv Gandhi International Stadium, Hyderabad']",25 SEP 2022,7:30 PM IST

# 4. Scrape the details of State-wise GDP of India from statisticstime.com

In [31]:
browser = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [32]:
browser.get('http://statisticstimes.com/')
browser.maximize_window()
time.sleep(3)

In [33]:
economy = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
from selenium.webdriver.common.action_chains import ActionChains
a = ActionChains(browser)
a.move_to_element(economy).perform()

In [34]:
india = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')
india.click()

In [35]:
browser.refresh()

In [36]:
economy = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/button')
from selenium.webdriver.common.action_chains import ActionChains
a = ActionChains(browser)
a.move_to_element(economy).perform()
india = browser.find_element_by_xpath('//*[@id="top"]/div[2]/div[2]/div/a[3]')
india.click()

In [38]:
table = browser.find_element_by_xpath("//div[@id='table_id_wrapper']")

In [39]:
table = table.text.split('\n')[3:-1]

In [40]:
Rank=[]
State=[]
GSDP_19_20=[]
GSDP_18_19=[]
Share=[]
GDP=[]
GSDP201112_19_20=[]
GSDP201112_18_19=[]

In [41]:
for i in range(len(table)):
    Rank.append(str(table[i].split(' ')[0]))
    
    if str(table[i].split(' ')[2]) == '&':
        if str(table[i].split(' ')[4]).isalpha():
            State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4]))
            GSDP_19_20.append(str(table[i].split(' ')[5]))
            GSDP_18_19.append(str(table[i].split(' ')[6]))
            Share.append(str(table[i].split(' ')[7]))
            GDP.append(str(table[i].split(' ')[8]))
            GSDP201112_19_20.append(str(table[i].split(' ')[9]))
            GSDP201112_18_19.append(str(table[i].split(' ')[10]))
        elif str(table[i].split(' ')[3]).isalpha():
            State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3]))
            GSDP_19_20.append(str(table[i].split(' ')[4]))
            GSDP_18_19.append(str(table[i].split(' ')[5]))
            Share.append(str(table[i].split(' ')[6]))
            GDP.append(str(table[i].split(' ')[7]))
            GSDP201112_19_20.append(str(table[i].split(' ')[8]))
            GSDP201112_18_19.append(str(table[i].split(' ')[9]))
        
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha() & str(table[i].split(' ')[4]).isalpha() & str(table[i].split(' ')[5]).isalpha():
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4])+' '+str(table[i].split(' ')[5]))
        GSDP_19_20.append(str(table[i].split(' ')[6]))
        GSDP_18_19.append(str(table[i].split(' ')[7]))
        Share.append(str(table[i].split(' ')[8]))
        GDP.append(str(table[i].split(' ')[9]))
        GSDP201112_19_20.append(str(table[i].split(' ')[10]))
        GSDP201112_18_19.append(str(table[i].split(' ')[11]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha() & str(table[i].split(' ')[4]).isalpha():           
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3])+' '+str(table[i].split(' ')[4]))
        GSDP_19_20.append(str(table[i].split(' ')[5]))
        GSDP_19_20.append(str(table[i].split(' ')[6]))
        GSDP_18_19.append(str(table[i].split(' ')[7]))
        Share.append(str(table[i].split(' ')[8]))
        GDP.append(str(table[i].split(' ')[9]))
        GSDP201112_19_20.append(str(table[i].split(' ')[10]))
        GSDP201112_18_19.append(str(table[i].split(' ')[11]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha() & str(table[i].split(' ')[3]).isalpha():           
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2])+' '+str(table[i].split(' ')[3]))
        GSDP_19_20.append(str(table[i].split(' ')[4]))
        GSDP_18_19.append(str(table[i].split(' ')[5]))
        Share.append(str(table[i].split(' ')[6]))
        GDP.append(str(table[i].split(' ')[7]))
        GSDP201112_19_20.append(str(table[i].split(' ')[8]))
        GSDP201112_18_19.append(str(table[i].split(' ')[9]))
    elif str(table[i].split(' ')[1]).isalpha() & str(table[i].split(' ')[2]).isalpha():
        State.append(str(table[i].split(' ')[1])+' '+str(table[i].split(' ')[2]))
        GSDP_19_20.append(str(table[i].split(' ')[3]))
        GSDP_18_19.append(str(table[i].split(' ')[4]))
        Share.append(str(table[i].split(' ')[5]))
        GDP.append(str(table[i].split(' ')[6]))
        GSDP201112_19_20.append(str(table[i].split(' ')[7]))
        GSDP201112_18_19.append(str(table[i].split(' ')[8]))
    elif str(table[i].split(' ')[1]).isalpha():
        State.append(str(table[i].split(' ')[1]))
        GSDP_19_20.append(str(table[i].split(' ')[2]))
        GSDP_18_19.append(str(table[i].split(' ')[3]))
        Share.append(str(table[i].split(' ')[4]))
        GDP.append(str(table[i].split(' ')[5]))
        GSDP201112_19_20.append(str(table[i].split(' ')[6]))
        GSDP201112_18_19.append(str(table[i].split(' ')[7]))

In [42]:
GSDP_19_20

['-',
 '1,845,853',
 '1,687,818',
 '-',
 '1,631,977',
 '1,253,832',
 '1,020,989',
 '972,782',
 '969,604',
 '906,672',
 '-',
 '856,112',
 '831,610',
 '611,804',
 '574,760',
 '521,275',
 '-',
 '329,180',
 '328,598',
 '-',
 '-',
 '165,472',
 '80,449',
 '55,984',
 '-',
 '38,253',
 '36,572',
 '32,496',
 '31,790',
 '-',
 '-',
 '26,503',
 '-']

In [43]:
print(len(Rank))
print(len(State))
print(len(GSDP_19_20))
print(len(GSDP_18_19))
print(len(Share))
print(len(GDP))
print(len(GSDP201112_19_20))
print(len(GSDP201112_18_19))

33
33
33
33
33
33
33
33

In [44]:
GSDP=pd.DataFrame()
GSDP['Rank'] = Rank
GSDP['State'] = State
GSDP['GSDP (Cr INR at Current prices) 19-20'] = GSDP_19_20
GSDP['GSDP (Cr INR at Current prices) 18-19'] = GSDP_18_19
GSDP['Share'] = Share
GSDP['GDP'] = GDP
GSDP['GSDP (Cr INR at 2011-12 prices) 19-20'] = GSDP201112_19_20
GSDP['GSDP (Cr INR at 2011-12 prices) 18-19'] = GSDP201112_18_19
GSDP

,Rank,State,GSDP (Cr INR at Current prices) 19-20,GSDP (Cr INR at Current prices) 18-19,Share,GDP,GSDP (Cr INR at 2011-12 prices) 19-20,GSDP (Cr INR at 2011-12 prices) 18-19
0,1,Maharashtra,-,"2,632,792",13.94%,399.921,-,"2,039,074"
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629,"1,312,929","1,215,307"
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726,"1,166,817","1,123,982"
3,4,Gujarat,-,"1,502,899",7.96%,228.290,-,"1,186,379"
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806,"1,156,039","1,091,077"
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556,"793,223","739,525"
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179,"711,627","677,428"
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083,"672,018","621,301"
8,9,Telangana,"969,604","861,031",4.56%,130.791,"663,258","612,828"
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977,"561,801","522,009"
10,11,Kerala,-,"781,653",4.14%,118.733,-,"559,412"
11,12,Delhi,"856,112","774,870",4.10%,117.703,"634,408","590,569"
12,13,Haryana,"831,610","734,163",3.89%,111.519,"572,240","531,085"
13,14,Bihar,"611,804","530,363",2.81%,80.562,"414,977","375,651"
14,15,Punjab,"574,760","526,376",2.79%,79.957,"418,868","397,669"
15,16,Odisha,"521,275","487,805",2.58%,74.098,"396,499","376,877"
16,17,Assam,-,"315,881",1.67%,47.982,-,"234,048"
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187,"243,477","231,182"
18,19,Jharkhand,"328,598","297,204",1.57%,45.145,"240,036","224,986"
19,20,Uttarakhand,-,"245,895",1.30%,37.351,-,"193,273"
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690,-,"112,755"
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369,"124,403","117,851"
22,23,Goa,"80,449","73,170",0.39%,11.115,"63,408","57,787"
23,24,Tripura,"55,984","49,845",0.26%,7.571,"40,583","36,963"
24,25,Chandigarh,-,"42,114",0.22%,6.397,-,"31,192"
25,26,Puducherry,"38,253","34,433",0.18%,5.230,"25,093","23,013"
26,27,Meghalaya,"36,572","33,481",0.18%,5.086,"26,695","24,682"
27,28,Sikkim,"32,496","28,723",0.15%,4.363,"20,017","18,722"
28,29,Manipur,"31,790","27,870",0.15%,4.233,"20,673","19,300"
29,30,Nagaland,-,"27,283",0.14%,4.144,-,"17,647"
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737,-,"16,676"
31,32,Mizoram,"26,503","22,287",0.12%,3.385,"18,797","16,478"
32,33,Andaman & Nicobar Islands,-,-,-,-,-,-

# 6. Scrape the details of top 100 songs on billiboard.com.

In [62]:
browser = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [63]:
browser.get('https:/www.billboard.com/')
browser.maximize_window()

In [65]:
charts = browser.find_element_by_xpath("//a[@class='c-link  lrv-a-unstyle-link lrv-a-unstyle-link lrv-u-color-brand-accent-blue:hover lrv-a-hover-effect lrv-u-whitespace-nowrap lrv-u-color-grey-lightest ']")
charts.click()

In [66]:
hot = browser.find_element_by_xpath("//a[@class='c-label__link lrv-u-color-brand-primary u-color-black@mobile-max a-font-primary-bold lrv-u-font-size-32 u-whitespace-nowrap@tablet']")
hot.click()

In [67]:
ranks= browser.find_elements_by_xpath("//li[@class='o-chart-results-list__item // lrv-u-background-color-black lrv-u-color-white u-width-100 u-width-55@mobile-max u-width-55@tablet-only lrv-u-height-100p lrv-u-flex lrv-u-flex-direction-column@mobile-max lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey']")
rank=[]
for i in ranks:
    rank.append(i.text)

In [68]:
song=[]
firstsong = browser.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 u-font-size-23@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-245 u-max-width-230@tablet-only u-letter-spacing-0028@tablet']")
song.append(firstsong[0].text)

In [69]:
songs = browser.find_elements_by_xpath("//h3[@class='c-title  a-no-trucate a-font-primary-bold-s u-letter-spacing-0021 lrv-u-font-size-18@tablet lrv-u-font-size-16 u-line-height-125 u-line-height-normal@mobile-max a-truncate-ellipsis u-max-width-330 u-max-width-230@tablet-only']")
for i in songs:
    song.append(i.text)

In [70]:
artist=[]
firstartists = browser.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only u-font-size-20@tablet']")
artist.append(firstartists[0].text)

In [71]:
artists = browser.find_elements_by_xpath("//span[@class='c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021 lrv-u-display-block a-truncate-ellipsis-2line u-max-width-330 u-max-width-230@tablet-only']")
for i in artists:
    artist.append(i.text)

In [72]:
lastweek=[]
peak_rank=[]
week=[]

In [73]:
lastweek_1= browser.find_elements_by_xpath("//span[@class='c-label  a-font-primary-bold-l a-font-primary-m@mobile-max u-font-weight-normal@mobile-max lrv-u-padding-tb-050@mobile-max u-font-size-32@tablet']")

In [74]:
lastweek.append(lastweek_1[0].text)
peak_rank.append(lastweek_1[1].text)
week.append(lastweek_1[2].text)

In [75]:
lastweek_all= browser.find_elements_by_xpath("//span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']")

In [76]:
config=[]
for i in lastweek_all:
    config.append(i.text)

In [77]:
temp_lastweek=config[0::6]
for i in temp_lastweek:
    lastweek.append(i)

In [78]:
temp_peakrank=config[1::6]
for i in temp_peakrank:
    peak_rank.append(i)

In [79]:
temp_week=config[2::6]
for i in temp_week:
    week.append(i)

In [80]:
hot_100=pd.DataFrame()
hot_100['Rank']= rank
hot_100['Song Name']=song
hot_100['Artist Name']=artist
hot_100['Last Week Rank']=lastweek
hot_100['Peak Rank']=peak_rank
hot_100['Weeks On Board']=week
hot_100

,Rank,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks On Board
0,1,Break My Soul,Beyonce,6,1,7
1,2,About Damn Time,Lizzo,1,1,16
2,3,As It Was,Harry Styles,2,1,18
3,4,Running Up That Hill (A Deal With God),Kate Bush,3,3,30
4,5,Wait For U,Future Featuring Drake & Tems,5,1,14
...,...,...,...,...,...,...
95,96,Until I Found You,Stephen Sanchez,88,88,5
96,97,Un Ratito,Bad Bunny,93,16,13
97,98,Best Thing Since Backroads,Jake Owen,72,72,4
98,99,La Corriente,Bad Bunny & Tony Dize,100,32,10
99,100,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,98,98,2

# 7. Scrape the details of Data science recruiters from naukri.com.

In [81]:
browser = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [82]:
browser.get('https://www.naukri.com/recruiters')
browser.maximize_window()

In [83]:
designation = browser.find_element_by_xpath("//input[@placeholder='Skills, Designations, Companies']")
designation.send_keys("Data Scientist")

In [84]:
search_button = browser.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']")
search_button.click()

In [85]:
name=[]
designation=[]
company=[]
skill=[]
loc=[]

In [86]:
rec_names = browser.find_elements_by_xpath("//span[@class='fl ellipsis']")
for i in rec_names:
    name.append(i.text)

In [87]:
rec_desig = browser.find_elements_by_xpath("//span[@class='ellipsis clr']")
for i in rec_desig:
    designation.append(i.text)

In [88]:
rec_temp = browser.find_elements_by_xpath("//a[@class='ellipsis']")

In [89]:
temp_cell=[]
for i in rec_temp:
    temp_cell.append(i.text)
company=temp_cell[1::2]

In [90]:
rec_skill = browser.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for i in rec_skill:
    skill.append(i.text)

In [91]:
rec_loc = browser.find_elements_by_xpath("//small[@class='ellipsis']")
counter=0
for i in rec_loc:
    if counter==35:
        loc.append('-')
        counter+=1
        loc.append(i.text)
    else:
        loc.append(i.text)
        counter+=1

In [92]:
naukri=pd.DataFrame()
naukri['Name']=name
naukri['Designation']=designation
naukri['Company']=company
naukri['Skills they hire for']=skill
naukri['Location']=loc
naukri

,Name,Designation,Company,Skills they hire for,Location
0,Tanushree,Lead Recruiter,RecRoots,"UI Developers, Software Engineers, Quality Ass...",Noida
1,sashi bhushan,Senior Specialist,Wipro,"pig, hbase, sas, spss, apache, python, nosql, ...",Bengaluru / Bangalore
2,Bitapi,HR and Operation Manager,Anvaya,"Hadoop, Big Data, Data Scientists, Java, Sprin...",Bengaluru / Bangalore
3,Gajendra Singh,Head of Recruitment - Product &amp;...,A Leading of Product Start-UP Company,"Data Scientist, Big Data, Hadoop, Web Analytic...",Noida
4,Sadashiv Kulkarni,Company HR,Digitially Insights Pvt Ltd,"Big Data Engineer, Data Scientist, Solutions, ...",Pune
5,Invelopment,Company HR,Invelopment,Scandinavian Startups,Ahmedabad
6,Anjali Srivastava,Director HR,CodeFire Technologies Pvt. Ltd.,"Technical, Business Development Executive, Sof...",Noida
7,Helly Vyas,HR Business Partner,AM - TA &amp; HR,"Big Data technology, PLSQL, Web Developer, Jav...",Pune
8,Ashish Verma,Senior Associate Human Resources,Evalueserve.com Private Limited,"SAS, VBA, Business Information Services(BIS), ...",Gurgaon
9,Balaji Prabhakaran,Company Recruiter,Oportun,"Technical Solution Architect, Data Scientist, ...",Chennai
10,Shiva Kumar N,Founder,Rapid Talent Solutions -9148242334,"salaesforce, Web Technologies, .net, .net full...",Bengaluru / Bangalore
11,Bhuwneshari Devi,Lead Talent Acquisition,Success Pact Consulting,"Amazon, Olacabs, Quikr, Bankbazzar, Uber, Flip...",Delhi
12,HS Sandesh,Talent Evangelist www staffiohr co,Staffio HR,"Digital Marketing, General Manager, Business D...",Bengaluru / Bangalore
13,Anoop Somarajan,Manager - Talent Acquisition,R1RCM,"Asp.net, Hl7, Mirth, Perl, Xamarin, Javascript...",Chennai
14,Datafoundry,Company HR,JAITRA SOFTWARE SOLUTIONS PVT LTD,"Webmethods Developer, Mean Stack, Business Ana...",Bengaluru / Bangalore
15,A Valsa Florina,Recruitment Specialist,Redbus.in,"Business Analyst, Front end developer, legal, ...",Bengaluru / Bangalore
16,Kalaivani M V,HR Manager,ZYUDLY LABS DATA SOLUTIONS PRIVATE LIMITED,"Data Scientist, Cloud Computing, Mobile Applic...",Chennai
17,Prashant K,Sr HR,Confidential,"Data Analyst, Statistical Analysis, Data Scien...",Bengaluru / Bangalore
18,Radhika,HR Associate,Bright Bridge Info-tech Pvt Ltd,"business analyst - IT (python), pay per click,...",Coimbatore
19,Rakhi,HR recruiter,Constalytics,"Data Scientist, Data Research Analyst, Big Dat...",Singapore - (singapore)
20,Monika Jain,Talent Aquistion Lead,Info Edge India Limited,"Lamp Developer, Ui/ux Developer, Qa Engineer, ...",Noida
21,Shefali Gupta,Recruitment Consultant,HUNTINGCUBE RECRUITMENT SOLUTIONS PRIVATE...,"Java, Python, Ror, Nodejs, React.js, Angularjs...",Noida
22,Trilok Nath,Senior IT Recruiter,Molveno Consulting Private Limited,".Net Developers With Angular Js, Html, Front E...",Hyderabad / Secunderabad
23,Rashmi Kathuria,Talent Acquisition Specialist (Specialized...,Mount Talent consulting,"Leading MNCs, Product based organizations",Noida
24,Vidya Rani Hadimani,Business Manager Delivery,Talent Management Labs Inc.,Amazon Walmart Adobe OLA Myntracom Komli Media...,Bengaluru / Bangalore
25,Monika Singh Thakur,Technical Recruiter,ValueLabs,"Big Data Analytics, Marketing Analytics, Full ...",Indore
26,Shikha Bakshi,Senior Manager Recruitment,Fractal Analytics!!,"Analytics, Big Data, Hadoop, Python",Gurgaon
27,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
28,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
29,Ravi,Team HR,Einfluss Teknocommercial Pvt. Ltd.,"Deep Learning, Machine Learning, unstructured ...",Ghaziabad
30,Sai Siddharth Chinta,Technical Recruiter,McKinsey &amp; Company,Not Specified,Bengaluru / Bangalore
31,Ishu Kumar,Co Founder &amp; Ceo,Data X,"Python, Machine Learning, Sql, Data Science",Bengaluru / Bangalore
32,Vivek Shrivastava,Assistant Manager Human Resources,InnovAccer Management Pvt Ltd,"Business Analyst, analytics, Decesion Scientis...",Noida
33,Gayathri E,Sr Recruitment,Wonderwrks IT Services Private Limited,"IT Infrastructure Management, PHP, Wordpress, ...",Chennai
34,Best In Town Analytics,Analytics Associate,BITA,Data Analytics,Bengaluru / Bangalore
35,Santhosh Nagaiah,Chief marketing officer,Tuple Technologies Pte Ltd,"Data Science, Project Management, Backend",-
36,priyanka,General Manager,Reliance Industries,"Sap, Saas, Sql, Hadoop, Production Planning, B...",Mumbai
37,Nagendla Syam Kumar,Data Scientist,FLOWERHORN IT PVT LTD,"Machine Learning, NLP, Performance Review, HR,...",Bengaluru / Bangalore
38,Renny Benita K,Operations Manager,DeepIQ Software Solutions Pvt Ltd,"Core Java, J2ee, Big Data, Machine Learning, D...",Bengaluru / Bangalore
39,Jamil Akhtar,Company Recruiter,Quikkloan,Not Specified,Delhi
40,Roshan Menugu,Company Recruiter,Cyient Limited,Not Specified,Hyderabad / Secunderabad
41,Sudipta Samanta,Founder,DataNnoviteSol LLP,Not Specified,Pune
42,HR Team,Company HR,Terra Blue Exploration Technologies Pvt....,Not Specified,Bengaluru / Bangalore
43,rajesh,HR Executive,quantum value IT services,"Data Scientist, Tableau, R Tool, Data Analytic...",Bengaluru / Bangalore
44,navya neluri,Data Scientist,asens labs,Not Specified,Hyderabad / Secunderabad
45,Ram Kumar,Data Scientist,Working As A Freelancer,Not Specified,Pune
46,Shreya Naithani,Talent Acquisition Executive,Purplejack Labs Pvt. Ltd.,"Node.js, React.js, Etl Testing, Data Warehousi...",Mumbai
47,Vanitha Senkurichi,Company HR,Quaero 3 India Ltd,"sql, Ui Development, ssis, Data Modeling, Data...",Bengaluru / Bangalore
48,Sravan Kumar Ranga,Assistant Manager,GSPANN Technologies,"devops, build and release, Delivery Manager, O...",Hyderabad / Secunderabad
49,Zack,Recruitment Manager,Perex Engineering Pvt Ltd,"Software Development, Javascript, Core Java, J...",Hyderabad / Secunderabad

# 10. Details of Datasets from UCI machine learning repositories.Url = https://archive.ics.uci.edu/.

In [108]:
driver=webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')
url='https://archive.ics.uci.edu/ml/index.php'
driver.get(url)

In [109]:
driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b').click()

In [110]:
name=[]
name_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a')
for i in name_tag:
    name.append(i.text)
print(len(name)) 
print(name)

622
['Abalone', 'Adult', 'Annealing', 'Anonymous Microsoft Web Data', 'Arrhythmia', 'Artificial Characters', 'Audiology (Original)', 'Audiology (Standardized)', 'Auto MPG', 'Automobile', 'Badges', 'Balance Scale', 'Balloons', 'Breast Cancer', 'Breast Cancer Wisconsin (Original)', 'Breast Cancer Wisconsin (Prognostic)', 'Breast Cancer Wisconsin (Diagnostic)', 'Pittsburgh Bridges', 'Car Evaluation', 'Census Income', 'Chess (King-Rook vs. King-Knight)', 'Chess (King-Rook vs. King-Pawn)', 'Chess (King-Rook vs. King)', 'Chess (Domain Theories)', 'Bach Chorales', 'Connect-4', 'Credit Approval', 'Japanese Credit Screening', 'Computer Hardware', 'Contraceptive Method Choice', 'Covertype', 'Cylinder Bands', 'Dermatology', 'Diabetes', 'DGP2 - The Second Data Generation Program', 'Document Understanding', 'EBL Domain Theories', 'Echocardiogram', 'Ecoli', 'Flags', 'Function Finding', 'Glass Identification', "Haberman's Survival", 'Hayes-Roth', 'Heart Disease', 'Hepatitis', 'Horse Colic', 'ICU', 'Image Segmentation', 'Internet Advertisements', 'Ionosphere', 'Iris', 'ISOLET', 'Kinship', 'Labor Relations', 'LED Display Domain', 'Lenses', 'Letter Recognition', 'Liver Disorders', 'Logic Theorist', 'Lung Cancer', 'Lymphography', 'Mechanical Analysis', 'Meta-data', 'Mobile Robots', 'Molecular Biology (Promoter Gene Sequences)', 'Molecular Biology (Protein Secondary Structure)', 'Molecular Biology (Splice-junction Gene Sequences)', "MONK's Problems", 'Moral Reasoner', 'Multiple Features', 'Mushroom', 'Musk (Version 1)', 'Musk (Version 2)', 'Nursery', 'Othello Domain Theory', 'Page Blocks Classification', 'Optical Recognition of Handwritten Digits', 'Pen-Based Recognition of Handwritten Digits', 'Post-Operative Patient', 'Primary Tumor', 'Prodigy', 'Qualitative Structure Activity Relationships', 'Quadruped Mammals', 'Servo', 'Shuttle Landing Control', 'Solar Flare', 'Soybean (Large)', 'Soybean (Small)', 'Challenger USA Space Shuttle O-Ring', 'Low Resolution Spectrometer', 'Spambase', 'SPECT Heart', 'SPECTF Heart', 'Sponge', 'Statlog Project', 'Student Loan Relational', 'Teaching Assistant Evaluation', 'Tic-Tac-Toe Endgame', 'Thyroid Disease', 'Trains', 'University', 'Congressional Voting Records', 'Water Treatment Plant', 'Waveform Database Generator (Version 1)', 'Waveform Database Generator (Version 2)', 'Wine', 'Yeast', 'Zoo', 'Undocumented', 'Twenty Newsgroups', 'Australian Sign Language signs', 'Australian Sign Language signs (High Quality)', 'US Census Data (1990)', 'Census-Income (KDD)', 'Coil 1999 Competition Data', 'Corel Image Features', 'E. Coli Genes', 'EEG Database', 'El Nino', 'Entree Chicago Recommendation Data', 'CMU Face Images', 'Insurance Company Benchmark (COIL 2000)', 'Internet Usage Data', 'IPUMS Census Database', 'Japanese Vowels', 'KDD Cup 1998 Data', 'KDD Cup 1999 Data', 'M. Tuberculosis Genes', 'Movie', 'MSNBC.com Anonymous Web Data', 'NSF Research Award Abstracts 1990-2003', 'Pioneer-1 Mobile Robot Data', 'Pseudo Periodic Synthetic Time Series', 'Reuters-21578 Text Categorization Collection', 'Robot Execution Failures', 'Synthetic Control Chart Time Series', 'Syskill and Webert Web Page Ratings', 'UNIX User Data', 'Volcanoes on Venus - JARtool experiment', 'Statlog (Australian Credit Approval)', 'Statlog (German Credit Data)', 'Statlog (Heart)', 'Statlog (Landsat Satellite)', 'Statlog (Image Segmentation)', 'Statlog (Shuttle)', 'Statlog (Vehicle Silhouettes)', 'Connectionist Bench (Nettalk Corpus)', 'Connectionist Bench (Sonar, Mines vs. Rocks)', 'Connectionist Bench (Vowel Recognition - Deterding Data)', 'Economic Sanctions', 'Protein Data', 'Cloud', 'CalIt2 Building People Counts', 'Dodgers Loop Sensor', 'Poker Hand', 'MAGIC Gamma Telescope', 'UJI Pen Characters', 'Mammographic Mass', 'Forest Fires', 'Reuters Transcribed Subset', 'Bag of Words', 'Concrete Compressive Strength', 'Hill-Valley', 'Arcene', 'Dexter', 'Dorothea', 'Gisette', 'Madelon', 'Ozone Level Detection', 'Abscisic Acid Signaling Network', 'Parkinsons', 'Character Trajectories', 'Blood Transfusion Service Center', 'UJI Pen Characters (Version 2)', 'Semeion Handwritten Digit', 'SECOM', 'Plants', 'Libras Movement', 'Concrete Slump Test', 'Communities and Crime', 'Acute Inflammations', 'Wine Quality', 'URL Reputation', 'p53 Mutants', 'Parkinsons Telemonitoring', 'Demospongiae', 'Opinosis Opinion ⁄ Review', 'Breast Tissue', 'Cardiotocography', 'Wall-Following Robot Navigation Data', 'Spoken Arabic Digit', 'Localization Data for Person Activity', 'AutoUniv', 'Steel Plates Faults', 'MiniBooNE particle identification', 'YearPredictionMSD', 'PEMS-SF', 'OpinRank Review Dataset', 'Relative location of CT slices on axial axis', 'Online Handwritten Assamese Characters Dataset', 'PubChem Bioassay Data', 'Record Linkage Comparison Patterns', 'Communities and Crime Unnormalized', 'Vertebral Column', 'EMG Physical Action Data Set', 'Vicon Physical Action Data Set', 'Amazon Commerce reviews set', 'Amazon Access Samples', 'Reuter_50_50', 'Farm Ads', 'DBWorld e-mails', 'KEGG Metabolic Relation Network (Directed)', 'KEGG Metabolic Reaction Network (Undirected)', 'Bank Marketing', 'YouTube Comedy Slam Preference Data', 'Gas Sensor Array Drift Dataset', 'ILPD (Indian Liver Patient Dataset)', 'OPPORTUNITY Activity Recognition', 'Nomao', 'SMS Spam Collection', 'Skin Segmentation', 'Planning Relax', 'PAMAP2 Physical Activity Monitoring', 'Restaurant & consumer data', 'CNAE-9', 'Individual household electric power consumption', 'seeds', 'Northix', 'QtyT40I10D100K', 'Legal Case Reports', 'Human Activity Recognition Using Smartphones', 'One-hundred plant species leaves data set', 'Energy efficiency', 'Yacht Hydrodynamics', 'Fertility', 'Daphnet Freezing of Gait', '3D Road Network (North Jutland, Denmark)', 'ISTANBUL STOCK EXCHANGE', 'Buzz in social media', 'First-order theorem proving', 'Wearable Computing: Classification of Body Postures and Movements (PUC-Rio)', 'Gas sensor arrays in open sampling settings', 'Climate Model Simulation Crashes', 'MicroMass', 'QSAR biodegradation', 'BLOGGER', 'Daily and Sports Activities', 'User Knowledge Modeling', 'Reuters RCV1 RCV2 Multilingual, Multiview Text Categorization Test collection', 'NYSK', 'Turkiye Student Evaluation', "ser Knowledge Modeling Data (Students' Knowledge Levels on DC Electrical Machines)", 'EEG Eye State', 'Physicochemical Properties of Protein Tertiary Structure', 'seismic-bumps', 'banknote authentication', 'USPTO Algorithm Challenge, run by NASA-Harvard Tournament Lab and TopCoder Problem: Pat', 'YouTube Multiview Video Games Dataset', 'Gas Sensor Array Drift Dataset at Different Concentrations', 'Activities of Daily Living (ADLs) Recognition Using Binary Sensors', 'SkillCraft1 Master Table Dataset', 'Weight Lifting Exercises monitored with Inertial Measurement Units', 'SML2010', 'Bike Sharing Dataset', 'Predict keywords activities in a online social media', 'Thoracic Surgery Data', 'EMG dataset in Lower Limb', 'SUSY', 'HIGGS', 'Qualitative_Bankruptcy', 'LSVT Voice Rehabilitation', 'Dataset for ADL Recognition with Wrist-worn Accelerometer', 'Wilt', 'User Identification From Walking Activity', 'Activity Recognition from Single Chest-Mounted Accelerometer', 'Leaf', 'Dresses_Attribute_Sales', 'Tamilnadu Electricity Board Hourly Readings', 'Airfoil Self-Noise', 'Wholesale customers', 'Twitter Data set for Arabic Sentiment Analysis', 'Combined Cycle Power Plant', 'Urban Land Cover', 'Diabetes 130-US hospitals for years 1999-2008', 'Bach Choral Harmony', 'StoneFlakes', 'Tennis Major Tournament Match Statistics', 'Parkinson Speech Dataset with Multiple Types of Sound Recordings', 'Gesture Phase Segmentation', 'Perfume Data', 'BlogFeedback', 'REALDISP Activity Recognition Dataset', 'Newspaper and magazine images segmentation dataset', 'AAAI 2014 Accepted Papers', 'Gas sensor array under flow modulation', 'Gas sensor array exposed to turbulent gas mixtures', 'UJIIndoorLoc', 'Sentence Classification', 'Dow Jones Index', 'sEMG for Basic Hand movements', 'AAAI 2013 Accepted Papers', 'Geographical Original of Music', 'Condition Based Maintenance of Naval Propulsion Plants', 'Grammatical Facial Expressions', 'NoisyOffice', 'MHEALTH Dataset', 'Student Performance', 'ElectricityLoadDiagrams20112014', 'Gas sensor array under dynamic gas mixtures', 'microblogPCU', 'Firm-Teacher_Clave-Direction_Classification', 'Dataset for Sensorless Drive Diagnosis', 'TV News Channel Commercial Detection Dataset', 'Phishing Websites', 'Greenhouse Gas Observing Network', 'Diabetic Retinopathy Debrecen Data Set', 'HIV-1 protease cleavage', 'Sentiment Labelled Sentences', 'Online News Popularity', 'Forest type mapping', 'wiki4HE', 'Online Video Characteristics and Transcoding Time Dataset', 'Chronic_Kidney_Disease', 'Machine Learning based ZZAlpha Ltd. Stock Recommendations 2012-2014', 'Folio', 'Taxi Service Trajectory - Prediction Challenge, ECML PKDD 2015', 'Cuff-Less Blood Pressure Estimation', 'Smartphone-Based Recognition of Human Activities and Postural Transitions', 'Mice Protein Expression', 'UJIIndoorLoc-Mag', 'Heterogeneity Activity Recognition', 'Educational Process Mining (EPM): A Learning Analytics Data Set', 'HEPMASS', 'Indoor User Movement Prediction from RSS data', 'Open University Learning Analytics dataset', 'default of credit card clients', 'Mesothelioma’s disease data set', 'Online Retail', 'SIFT10M', 'GPS Trajectories', 'Detect Malacious Executable(AntiVirus)', 'Occupancy Detection', 'Improved Spiral Test Using Digitized Graphics Tablet for Monitoring Parkinson’s Disease', 'News Aggregator', 'Air Quality', 'Twin gas sensor arrays', 'Gas sensors for home activity monitoring', 'Facebook Comment Volume Dataset', 'Smartphone Dataset for Human Activity Recognition (HAR) in Ambient Assisted Living (AAL)', 'Polish companies bankruptcy data', 'Activity Recognition system based on Multisensor data fusion (AReM)', 'Dota2 Games Results', 'Facebook metrics', 'UbiqLog (smartphone lifelogging)', 'NIPS Conference Papers 1987-2015', 'HTRU2', 'Drug consumption (quantified)', 'Appliances energy prediction', 'Miskolc IIS Hybrid IPS', 'KDC-4007 dataset Collection', 'Geo-Magnetic field and WLAN dataset for indoor localisation from wristband and smartphone', 'DrivFace', 'Website Phishing', 'YouTube Spam Collection', 'Beijing PM2.5 Data', 'Cargo 2000 Freight Tracking and Tracing', 'Cervical cancer (Risk Factors)', 'Quality Assessment of Digital Colposcopies', 'KASANDR', 'FMA: A Dataset For Music Analysis', 'Air quality', 'Epileptic Seizure Recognition', 'Devanagari Handwritten Character Dataset', 'Stock portfolio performance', 'MoCap Hand Postures', 'Early biomarkers of Parkinson�s disease based on natural connected speech', 'Data for Software Engineering Teamwork Assessment in Education Setting', 'PM2.5 Data of Five Chinese Cities', 'Parkinson Disease Spiral Drawings Using Digitized Graphics Tablet', 'Sales_Transactions_Dataset_Weekly', 'Las Vegas Strip', 'Eco-hotel', 'MEU-Mobile KSD', 'Crowdsourced Mapping', 'gene expression cancer RNA-Seq', 'Hybrid Indoor Positioning Dataset from WiFi RSSI, Bluetooth and magnetometer', 'chestnut – LARVIC', 'Burst Header Packet (BHP) flooding attack on Optical Burst Switching (OBS) Network', 'Motion Capture Hand Postures', 'Anuran Calls (MFCCs)', 'TTC-3600: Benchmark dataset for Turkish text categorization', 'Gastrointestinal Lesions in Regular Colonoscopy', 'Daily Demand Forecasting Orders', 'Paper Reviews', 'extention of Z-Alizadeh sani dataset', 'Z-Alizadeh Sani', 'Dynamic Features of VirusShare Executables', 'IDA2016Challenge', 'DSRC Vehicle Communications', 'Mturk User-Perceived Clusters over Images', 'Character Font Images', 'DeliciousMIL: A Data Set for Multi-Label Multi-Instance Learning with Instance Labels', 'Autistic Spectrum Disorder Screening Data for Children', 'Autistic Spectrum Disorder Screening Data for Adolescent', 'APS Failure at Scania Trucks', 'Wireless Indoor Localization', 'HCC Survival', 'CSM (Conventional and Social Media Movies) Dataset 2014 and 2015', 'University of Tehran Question Dataset 2016 (UTQD.2016)', 'Autism Screening Adult', 'Activity recognition with healthy older people using a batteryless wearable sensor', 'Immunotherapy Dataset', 'Cryotherapy Dataset', 'OCT data & Color Fundus Images of Left & Right Eyes', 'Discrete Tone Image Dataset', 'News Popularity in Multiple Social Media Platforms', 'Ultrasonic flowmeter diagnostics', 'ICMLA 2014 Accepted Papers Data Set', 'BLE RSSI Dataset for Indoor localization and Navigation', 'Container Crane Controller Data Set', 'Residential Building Data Set', 'Health News in Twitter', 'chipseq', 'SGEMM GPU kernel performance', 'Repeat Consumption Matrices', 'detection_of_IoT_botnet_attacks_N_BaIoT', 'Absenteeism at work', 'SCADI', 'Condition monitoring of hydraulic systems', 'Carbon Nanotubes', 'Optical Interconnection Network', 'Sports articles for objectivity analysis', 'Breast Cancer Coimbra', 'GNFUV Unmanned Surface Vehicles Sensor Data', 'Dishonest Internet users Dataset', 'Victorian Era Authorship Attribution', 'Simulated Falls and Daily Living Activities Data Set', 'Multimodal Damage Identification for Humanitarian Computing', 'EEG Steady-State Visual Evoked Potential Signals', 'Roman Urdu Data Set', 'Avila', 'PANDOR', 'Drug Review Dataset (Druglib.com)', 'Drug Review Dataset (Drugs.com)', 'Physical Unclonable Functions', 'Superconductivty Data', 'WESAD (Wearable Stress and Affect Detection)', 'GNFUV Unmanned Surface Vehicles Sensor Data Set 2', 'Student Academics Performance', 'Online Shoppers Purchasing Intention Dataset', 'PMU-UD', "Parkinson's Disease Classification", 'Electrical Grid Stability Simulated Data', 'Caesarian Section Classification Dataset', 'BAUM-1', 'BAUM-2', 'Audit Data', 'BuddyMove Data Set', 'Real estate valuation data set', 'Early biomarkers of Parkinson’s disease based on natural connected speech Data Set', 'Somerville Happiness Survey', '2.4 GHZ Indoor Channel Measurements', 'EMG data for gestures', 'Parking Birmingham', 'Behavior of the urban traffic of the city of Sao Paulo in Brazil', 'Travel Reviews', 'Tarvel Review Ratings', 'Rice Leaf Diseases', 'Gas sensor array temperature modulation', 'Facebook Live Sellers in Thailand', 'Parkinson Dataset with replicated acoustic features', 'Metro Interstate Traffic Volume', 'Query Analytics Workloads Dataset', 'Wave Energy Converters', 'PPG-DaLiA', 'Alcohol QCM Sensor Dataset', 'Divorce Predictors data set', 'Incident management process enriched event log', 'Opinion Corpus for Lebanese Arabic Reviews (OCLAR)', 'MEx', 'Beijing Multi-Site Air-Quality Data', 'Online Retail II', 'Hepatitis C Virus (HCV) for Egyptian patients', 'QSAR fish toxicity', 'QSAR aquatic toxicity', 'Human Activity Recognition from Continuous Ambient Sensor Data', 'WISDM Smartphone and Smartwatch Activity and Biometrics Dataset', 'QSAR oral toxicity', 'QSAR androgen receptor', 'QSAR Bioconcentration classes dataset', 'QSAR fish bioconcentration factor (BCF)', 'A study of Asian Religious and Biblical Texts', 'Real-time Election Results: Portugal 2019', 'Bias correction of numerical prediction model temperature forecast', 'Bar Crawl: Detecting Heavy Drinking', 'Kitsune Network Attack Dataset', 'Shoulder Implant X-Ray Manufacturer Classification', 'Speaker Accent Recognition', 'Heart failure clinical records', 'Deepfakes: Medical Image Tamper Detection', 'selfBACK', 'South German Credit', 'Exasens', 'Swarm Behaviour', 'Crop mapping using fused optical-radar data set', 'BitcoinHeistRansomwareAddressDataset', 'Facebook Large Page-Page Network', 'Amphibians', 'Early stage diabetes risk prediction dataset.', 'Turkish Spam V01', 'Stock keeping units', 'Demand Forecasting for a store', 'Detect Malware Types', 'Wave Energy Converters', 'Youtube cookery channels viewers comments in Hinglish', 'Pedestrian in Traffic Dataset', 'Cervical Cancer Behavior Risk', 'Sattriya_Dance_Single_Hand_Gestures Dataset', 'Divorce Predictors data set', '3W dataset', 'Malware static and dynamic features VxHeaven and Virus Total', 'Internet Firewall Data', 'User Profiling and Abusive Language Detection Dataset', 'Estimation of obesity levels based on eating habits and physical condition', 'Rice (Cammeo and Osmancik)', 'Vehicle routing and scheduling problems', 'Algerian Forest Fires Dataset', 'Breath Metabolomics', 'Horton General Hospital', 'UrbanGB, urban road accidents coordinates labelled by the urban center', 'Gas Turbine CO and NOx Emission Data Set', 'Activity recognition using wearable physiological measurements', 'clickstream data for online shopping', 'CNNpred: CNN-based stock market prediction using a diverse set of variables', 'Apartment for rent classified', ': Simulated Data set of Iraqi tourism places', 'Nasarian CAD Dataset', 'Monolithic Columns in Troad and Mysia Region', 'Bar Crawl: Detecting Heavy Drinking', 'Seoul Bike Sharing Demand', 'Person Classification Gait Data', 'Shill Bidding Dataset', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Bone marrow transplant: children', 'Exasens', 'COVID-19 Surveillance', 'Refractive errors', 'Shoulder Implant X-Ray Manufacturer Classification', 'CLINC150', 'HCV data', 'Taiwanese Bankruptcy Prediction', 'South German Credit (UPDATE)', 'IIWA14-R820-Gazebo-Dataset-10Trajectories', 'Guitar Chords finger positions', 'Russian Corpus of Biographical Texts', 'Codon usage', 'Intelligent Media Accelerometer and Gyroscope (IM-AccGyro) Dataset', 'Myocardial infarction complications', 'Hungarian Chickenpox Cases', 'Simulated data for survival modelling', 'Student Performance on an entrance examination', 'Chemical Composition of Ceramic Samples', 'Labeled Text Forum Threads Dataset', 'Stock keeping units', 'BLE RSSI dataset for Indoor localization', 'Basketball dataset', 'GitHub MUSAE', 'Anticancer peptides', 'Monolithic Columns in Troad and Mysia Region', 'Gender by Name', 'Iranian Churn Dataset', 'Unmanned Aerial Vehicle (UAV) Intrusion Detection', 'Shoulder Implant Manufacture Classification', 'LastFM Asia Social Network', 'Wheat kernels', 'Productivity Prediction of Garment Employees', 'Multi-view Brain Networks', 'LastFM Asia Social Network', 'Wisesight Sentiment Corpus', 'AI4I 2020 Predictive Maintenance Dataset', 'Dry Bean Dataset', 'in-vehicle coupon recommendation', 'Gait Classification', 'Wikipedia Math Essentials', 'Wikipedia Math Essentials', 'Synchronous Machine Data Set', 'Average Localization Error (ALE) in sensor node localization process in WSNs', '9mers from cullpdb', 'TamilSentiMix', 'Accelerometer', 'Synchronous Machine Data Set', 'Pedal Me Bicycle Deliveries', 'Turkish Headlines Dataset', 'Secondary Mushroom Dataset', 'Power consumption of Tetouan city', 'Raisin Dataset', 'Steel Industry Energy Consumption Dataset', 'Gender Gap in Spanish WP', 'Non verbal tourists data', 'Roman Urdu Sentiment Analysis Dataset (RUSAD)', 'TUANDROMD ( Tezpur University Android Malware Dataset)', 'Higher Education Students Performance Evaluation Dataset', 'Risk Factor prediction of Chronic Kidney Disease', 'Lab Test', 'Shoulder Implant Manufacture Classification', 'Rocket League Skillshots Data Set', 'Sepsis survival minimal clinical records', 'Water Quality Prediction', 'Traffic Flow Forecasting', 'sentiment analysis in Saudi Arabia about distance education during Covid-19', 'Kain Tradisional Sambas', 'Image Recognition Task Execution Times in Mobile Edge Computing', 'REWEMA', 'REJAFADA', 'Steel Industry Energy Consumption Dataset', 'Influenza outbreak event prediction via Twitter data', 'Turkish Music Emotion Dataset', 'Maternal Health Risk Data Set', 'Room Occupancy Estimation', 'Image Recognition Task Execution Times in Mobile Edge Computing']

In [111]:
d_type=[]
d_type_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]/p')
for i in d_type_tag[1:]:
    d_type.append(i.text)
print(len(d_type)) 
print(d_type)

622
['Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Univariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Univariate, Time-Series ', 'Multivariate, Spatial ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Data-Generator ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Sequential, Domain-Theory ', 'Sequential ', 'Sequential, Domain-Theory ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Domain-Theory ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate, Domain-Theory ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Data-Generator ', 'Multivariate, Data-Generator ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Time-Series ', 'Spatio-temporal ', 'Transactional, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Relational ', 'Multivariate, Relational ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', 'Univariate, Time-Series ', 'Text ', 'Multivariate, Time-Series ', 'Time-Series ', 'Multivariate, Text ', 'Text, Sequential ', 'Image ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Domain-Theory ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Text ', 'Text ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Domain-Theory ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate, Text, Domain-Theory ', 'Time-Series, Domain-Theory ', 'Multivariate, Text, Domain-Theory ', 'Text ', 'Text ', 'Multivariate, Univariate, Text ', 'Multivariate, Univariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate, Text, Domain-Theory ', 'Univariate ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate, Text ', 'Sequential ', 'Text ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Sequential, Text ', 'Multivariate, Univariate, Time-Series ', 'Time-Series, Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Domain-Theory ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Text ', 'Univariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Univariate, Sequential, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series, Domain-Theory ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series, Domain-Theory ', 'Multivariate, Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate, Time-Series ', 'Multivariate, Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', ' ', 'Text ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Time-Series ', 'Text ', ' ', ' ', 'Multivariate, Time-Series ', 'Multivariate ', 'Sequential, Text ', 'Multivariate, Text ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', ' ', 'Sequential ', 'Univariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Univariate, Domain-Theory ', 'Multivariate ', 'Text ', 'Sequential ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Text ', 'Time-Series ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Univariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Time-Series ', 'Multivariate, Univariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Text ', 'Multivariate, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Sequential ', 'Text ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series, Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series, Text ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Sequential, Time-Series ', 'Multivariate, Univariate ', 'Multivariate ', 'Multivariate, Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate, Time-Series ', 'Univariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Sequential ', 'Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Text ', 'Text ', 'Multivariate ', 'Time-Series ', 'Multivariate ', 'Time-Series ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Sequential, Time-Series ', 'Time-Series ', 'Multivariate ', 'Sequential ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate, Text ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Time-Series ', 'Multivariate ', 'Multivariate ', 'Sequential ', ' ', 'Multivariate ', 'Multivariate ', 'Time-Series ', 'Text ', 'Univariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Text ', 'Multivariate ', 'Univariate, Sequential, Time-Series ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', 'Multivariate ', ' ', 'Multivariate, Time-Series ', 'Univariate ']

In [112]:
task=[]
task_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]/p')
for i in task_tag[1:]:
    task.append(i.text)
print(len(task)) 
print(task)

622
['Classification ', 'Classification ', 'Classification ', 'Recommender-Systems ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Function-Learning ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Relational-Learning ', ' ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', ' ', 'Classification ', 'Classification ', 'Clustering ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Recommender-Systems ', 'Classification ', 'Regression, Description ', ' ', ' ', 'Classification ', 'Regression ', 'Classification ', ' ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Classification ', ' ', ' ', ' ', ' ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', ' ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', ' ', 'Classification ', 'Regression, Clustering ', 'Classification, Clustering ', 'Classification ', ' ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering ', 'Classification, Regression ', 'Regression, Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering, Causa ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Regression ', ' ', 'Classification ', ' ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression, Clustering ', 'Classification, Regression ', 'Classification, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Regression, Clustering, Causal-Discovery ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Causal-Discovery ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Causal-Discovery ', 'Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Causal-Discovery ', 'Classification, Clustering ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Regression ', 'Classification, Regression, Clustering ', 'Clustering ', 'Classification, Regression ', ' ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Clustering ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification, Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Recommendation ', 'Classification, Regression, Clustering ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression ', 'Clustering ', 'Classification ', 'Regression ', 'Regression, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification, Clustering ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification, Clustering, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Clustering ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification ', 'Clustering ', 'Classification, Regression ', 'Classification, Clustering ', 'Causal-Discovery ', 'Clustering ', 'Regression, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification, Regression, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Clustering ', 'Classification, Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification, Regression, Causal-Discovery ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Regression ', 'Regression ', 'Classification, Regression ', 'Classification ', 'Classification, Regression ', 'Regression ', 'Regression ', 'Classification, Clustering ', 'Classification ', 'Regression ', 'Classification ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Classification, Regression ', 'Classification, Regression, Clustering ', 'Classification ', 'Classification ', 'Classification ', 'Regression ', 'Regression ', 'Classification ', 'Classification, Clustering ', 'Regression ', 'Classification ', 'Classification ', 'Regression ', 'Classification ', 'Classification ', 'Classification ', 'Classification ', 'Regression ']

In [113]:
att_type=[]
att_type_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]/p')
for i in att_type_tag[1:]:
    att_type.append(i.text)
print(len(att_type)) 
print(att_type)

622
['Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical, Real ', 'Categorical, Integer, Real ', ' ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Real ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Real, Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', ' ', ' ', 'Categorical, Integer, Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Real ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Integer ', 'Categorical, Integer, Real ', ' ', 'Integer ', 'Categorical ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical, Integer, Real ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', ' ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Integer ', 'Categorical ', ' ', 'Integer, Real ', 'Integer ', 'Integer ', 'Categorical, Integer ', 'Categorical ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical ', 'Categorical ', 'Categorical ', 'Categorical ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Integer ', 'Categorical ', 'Categorical, Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Categorical, Integer ', ' ', ' ', 'Categorical, Real ', 'Real ', 'Categorical ', 'Categorical, Integer ', 'Categorical, Real ', 'Real ', ' ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Categorical ', 'Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', ' ', ' ', 'Categorical ', ' ', 'Categorical, Real ', ' ', 'Categorical ', 'Integer ', 'Real ', 'Categorical ', ' ', ' ', 'Categorical, Integer, Real ', 'Categorical, Integer ', 'Categorical, Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Categorical ', 'Real ', 'Real ', ' ', ' ', 'Real ', 'Categorical, Integer ', 'Categorical, Integer ', 'Categorical, Integer ', 'Real ', 'Integer ', 'Integer ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Categorical ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Categorical, Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', ' ', 'Integer ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Categorical ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', 'Integer, Real ', ' ', 'Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Integer ', 'Integer ', 'Integer ', ' ', 'Real ', 'Categorical ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', ' ', 'Integer, Real ', 'Real ', 'Integer ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Integer ', ' ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer, Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer, Real ', 'Integer ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Integer, Real ', ' ', ' ', 'Integer, Real ', 'Integer ', ' ', 'Real ', ' ', 'Real ', 'Integer ', ' ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Real ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', ' ', ' ', 'Real ', 'Real ', 'Integer, Real ', 'Real ', ' ', 'Integer ', 'Real ', 'Integer, Real ', 'Integer ', ' ', 'Integer ', 'Real ', ' ', 'Integer, Real ', 'Integer ', 'Integer, Real ', 'Integer ', ' ', ' ', ' ', 'Real ', 'Real ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Integer ', 'Integer, Real ', 'Integer ', 'Integer ', ' ', ' ', 'Real ', ' ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer, Real ', 'Integer ', ' ', ' ', 'Real ', 'Integer, Real ', ' ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', 'Real ', ' ', 'Integer, Real ', 'Real ', 'Real ', ' ', 'Real ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer, Real ', 'Integer, Real ', ' ', 'Integer ', 'Integer ', 'Real ', ' ', ' ', 'Real ', 'Integer ', 'Real ', 'Real ', 'Integer ', ' ', 'Real ', 'Integer ', 'Integer ', 'Integer ', 'Integer, Real ', 'Integer, Real ', ' ', 'Real ', 'Real ']

In [114]:
instances=[]
instances_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')
for i in instances_tag[1:]:
    instances.append(i.text)
print(len(instances)) 
print(instances)

622
['4177 ', '48842 ', '798 ', '37711 ', '452 ', '6000 ', '226 ', '226 ', '398 ', '205 ', '294 ', '625 ', '16 ', '286 ', '699 ', '198 ', '569 ', '108 ', '1728 ', '48842 ', ' ', '3196 ', '28056 ', ' ', '100 ', '67557 ', '690 ', '125 ', '209 ', '1473 ', '581012 ', '512 ', '366 ', ' ', ' ', ' ', ' ', '132 ', '336 ', '194 ', '352 ', '214 ', '306 ', '160 ', '303 ', '155 ', '368 ', ' ', '2310 ', '3279 ', '351 ', '150 ', '7797 ', '104 ', '57 ', ' ', '24 ', '20000 ', '345 ', ' ', '32 ', '148 ', '209 ', '528 ', ' ', '106 ', '128 ', '3190 ', '432 ', '202 ', '2000 ', '8124 ', '476 ', '6598 ', '12960 ', ' ', '5473 ', '5620 ', '10992 ', '90 ', '339 ', ' ', ' ', ' ', '167 ', '15 ', '1389 ', '307 ', '47 ', '23 ', '531 ', '4601 ', '267 ', '267 ', '76 ', ' ', '1000 ', '151 ', '958 ', '7200 ', '10 ', '285 ', '435 ', '527 ', '5000 ', '5000 ', '178 ', '1484 ', '101 ', ' ', '20000 ', '6650 ', '2565 ', '2458285 ', '299285 ', '340 ', '68040 ', ' ', '122 ', '178080 ', '50672 ', '640 ', '9000 ', '10104 ', '256932 ', '640 ', '191779 ', '4000000 ', ' ', '10000 ', '989818 ', '129000 ', ' ', '100000 ', '21578 ', '463 ', '600 ', '332 ', ' ', ' ', '690 ', '1000 ', '270 ', '6435 ', '2310 ', '58000 ', '946 ', '20008 ', '208 ', '528 ', ' ', ' ', '1024 ', '10080 ', '50400 ', '1025010 ', '19020 ', '1364 ', '961 ', '517 ', '200 ', '8000000 ', '1030 ', '606 ', '900 ', '2600 ', '1950 ', '13500 ', '4400 ', '2536 ', '300 ', '197 ', '2858 ', '748 ', '11640 ', '1593 ', '1567 ', '22632 ', '360 ', '103 ', '1994 ', '120 ', '4898 ', '2396130 ', '16772 ', '5875 ', '503 ', '51 ', '106 ', '2126 ', '5456 ', '8800 ', '164860 ', ' ', '1941 ', '130065 ', '515345 ', '440 ', ' ', '53500 ', '8235 ', ' ', '5749132 ', '2215 ', '310 ', '10000 ', '3000 ', '1500 ', '30000 ', '2500 ', '4143 ', '64 ', '53414 ', '65554 ', '45211 ', '1138562 ', '13910 ', '583 ', '2551 ', '34465 ', '5574 ', '245057 ', '182 ', '3850505 ', '138 ', '1080 ', '2075259 ', '210 ', '115 ', '3960456 ', ' ', '10299 ', '1600 ', '768 ', '308 ', '100 ', '237 ', '434874 ', '536 ', '140000 ', '6118 ', '165632 ', '18000 ', '540 ', '931 ', '1055 ', '100 ', '9120 ', '403 ', '111740 ', '10421 ', '5820 ', '403 ', '14980 ', '45730 ', '2584 ', '1372 ', '306 ', '120000 ', '13910 ', '2747 ', '3395 ', '39242 ', '4137 ', '17389 ', '51 ', '470 ', '132 ', '5000000 ', '11000000 ', '250 ', '126 ', ' ', '4889 ', ' ', ' ', '340 ', '501 ', '45781 ', '1503 ', '440 ', '2000 ', '9568 ', '168 ', '100000 ', '5665 ', '79 ', '127 ', '1040 ', '9900 ', '560 ', '60021 ', '1419 ', '101 ', '399 ', '58 ', '180 ', '21048 ', ' ', '750 ', '3000 ', '150 ', '1059 ', '11934 ', '27965 ', '216 ', '120 ', '649 ', '370 ', '4178504 ', '221579 ', '10800 ', '58509 ', '129685 ', '2456 ', '2921 ', '1151 ', '6590 ', '3000 ', '39797 ', '326 ', '913 ', '168286 ', '400 ', '314080 ', '637 ', '1710671 ', '12000 ', '10929 ', '1080 ', '40000 ', '43930257 ', '230318 ', '10500000 ', '13197 ', ' ', '30000 ', '324 ', '541909 ', '11164866 ', '163 ', '373 ', '20560 ', '40 ', '422937 ', '9358 ', '640 ', '919438 ', '40949 ', '5744 ', '10503 ', '42240 ', '102944 ', '500 ', '9782222 ', '11463 ', '17898 ', '1885 ', '19735 ', '1540 ', '4007 ', '153540 ', '606 ', '1353 ', '1956 ', '43824 ', '3942 ', '858 ', '287 ', '17764280 ', '106574 ', '9358 ', '11500 ', '92000 ', '315 ', '78095 ', '130 ', '74 ', '52854 ', '77 ', '811 ', '504 ', '401 ', '2856 ', '10546 ', '801 ', '1540 ', '1451 ', '1075 ', '78095 ', '7195 ', '3600 ', '76 ', '60 ', '405 ', '303 ', '303 ', '107888 ', '76000 ', '10000 ', '180 ', '745000 ', '12234 ', '292 ', '104 ', '60000 ', '2000 ', '165 ', '217 ', '1175 ', '704 ', '75128 ', '90 ', '90 ', '50 ', '71 ', '93239 ', '540 ', '105 ', '6611 ', '15 ', '372 ', '58000 ', '4960 ', '241600 ', '130000 ', '7062606 ', '740 ', '70 ', '2205 ', '10721 ', '640 ', '1000 ', '116 ', '1672 ', '322 ', '93600 ', '3060 ', '5879 ', '9200 ', '20000 ', '20867 ', ' ', '4143 ', '215063 ', '6000000 ', '21263 ', '63000000 ', '10190 ', '300 ', '12330 ', '5180 ', '756 ', '10000 ', '80 ', '1184 ', '1047 ', '777 ', '249 ', '414 ', ' ', '143 ', '7840 ', '30000 ', '35717 ', '135 ', '980 ', '5456 ', '120 ', '4095000 ', '7051 ', '240 ', '48204 ', '260000 ', '288000 ', '8300000 ', '125 ', '170 ', '141712 ', '3916 ', '6262 ', '420768 ', '1067371 ', '1385 ', '908 ', '546 ', '13956534 ', '15630426 ', '8992 ', '1687 ', '779 ', '1056 ', '590 ', '21643 ', '7750 ', '14057567 ', '27170754 ', '597 ', '329 ', '299 ', '20000 ', '26136 ', '1000 ', '399 ', '24017 ', '325834 ', '2916697 ', '22470 ', '189 ', '520 ', '826 ', '2279 ', '28764 ', '7107 ', '288000 ', '9800 ', '4760 ', '72 ', '1450 ', '170 ', '1984 ', '2955 ', '65532 ', '65919 ', '2111 ', '3810 ', '18 ', '244 ', '104 ', '139 ', '360177 ', '36733 ', '4480 ', '165474 ', '1985 ', '10000 ', '232 ', '150 ', '11 ', '14057567 ', '8760 ', '48 ', '6321 ', '3150 ', '17256 ', '187 ', '399 ', '14 ', '467 ', '597 ', '23700 ', '615 ', '6819 ', '1000 ', ' ', '2633 ', '200 ', '13028 ', '800 ', '1700 ', '521 ', '120000 ', '666 ', '88 ', '200 ', '2279 ', '23570 ', '10000 ', '37700 ', '1850 ', '11 ', '147270 ', '3150 ', '17256 ', '597 ', '7624 ', '314 ', '1197 ', '70 ', '7624 ', '26737 ', '10000 ', '13611 ', '12684 ', '48 ', '731 ', '731 ', '557 ', '107 ', '158716 ', '15744 ', '153000 ', '557 ', '36 ', '4200 ', '61069 ', '52417 ', '900 ', '35040 ', '4746 ', '73 ', '11000 ', '4465 ', '145 ', '202 ', '221 ', '597 ', '298 ', '110341 ', '705 ', '2101 ', '1765 ', '150 ', '4000 ', '6272 ', '1996 ', '35040 ', '75840 ', '400 ', '1014 ', '10129 ', '4000 ']

In [115]:
attributes=[]
attributes_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')
for i in attributes_tag[1:]:
    attributes.append(i.text)
print(len(attributes)) 
print(attributes)

622
['8 ', '14 ', '38 ', '294 ', '279 ', '7 ', ' ', '69 ', '8 ', '26 ', '1 ', '4 ', '4 ', '9 ', '10 ', '34 ', '32 ', '13 ', '6 ', '14 ', '22 ', '36 ', '6 ', ' ', '6 ', '42 ', '15 ', ' ', '9 ', '9 ', '54 ', '39 ', '33 ', '20 ', ' ', ' ', ' ', '12 ', '8 ', '30 ', ' ', '10 ', '3 ', '5 ', '75 ', '19 ', '27 ', ' ', '19 ', '1558 ', '34 ', '4 ', '617 ', '12 ', '16 ', '7 ', '4 ', '16 ', '7 ', ' ', '56 ', '18 ', '8 ', '22 ', ' ', '58 ', ' ', '61 ', '7 ', ' ', '649 ', '22 ', '168 ', '168 ', '8 ', ' ', '10 ', '64 ', '16 ', '8 ', '17 ', ' ', ' ', '72 ', '4 ', '6 ', '10 ', '35 ', '35 ', '4 ', '102 ', '57 ', '22 ', '44 ', '45 ', ' ', ' ', '5 ', '9 ', '21 ', '32 ', '17 ', '16 ', '38 ', '21 ', '40 ', '13 ', '8 ', '17 ', ' ', ' ', '15 ', '22 ', '68 ', '40 ', '17 ', '89 ', ' ', '4 ', '12 ', ' ', ' ', '86 ', '72 ', '61 ', '12 ', '481 ', '42 ', ' ', ' ', ' ', ' ', ' ', ' ', '5 ', '90 ', ' ', '5 ', ' ', ' ', '14 ', '20 ', '13 ', '36 ', '19 ', '9 ', '18 ', '4 ', '60 ', '10 ', ' ', ' ', '10 ', '4 ', '3 ', '11 ', '11 ', ' ', '6 ', '13 ', ' ', '100000 ', '9 ', '101 ', '10000 ', '20000 ', '100000 ', '5000 ', '500 ', '73 ', '43 ', '23 ', '3 ', '5 ', ' ', '256 ', '591 ', '70 ', '91 ', '10 ', '128 ', '6 ', '12 ', '3231961 ', '5409 ', '26 ', ' ', ' ', '10 ', '23 ', '24 ', '13 ', '8 ', ' ', '27 ', '50 ', '90 ', '138672 ', ' ', '386 ', ' ', ' ', '12 ', '147 ', '6 ', '8 ', '27 ', '10000 ', '20000 ', '10000 ', '54877 ', '4702 ', '24 ', '29 ', '17 ', '3 ', '128 ', '10 ', '242 ', '120 ', ' ', '4 ', '13 ', '52 ', '47 ', '857 ', '9 ', '7 ', '200 ', '4 ', ' ', '561 ', '64 ', '8 ', '7 ', '10 ', '9 ', '4 ', '8 ', '77 ', '51 ', '18 ', '1950000 ', '18 ', '1300 ', '41 ', '6 ', '5625 ', '5 ', ' ', '7 ', '33 ', '5 ', '15 ', '9 ', '19 ', '5 ', '5 ', '1000000 ', '129 ', ' ', '20 ', '152 ', '24 ', '16 ', '35 ', '17 ', '5 ', '18 ', '28 ', '7 ', '309 ', '3 ', '6 ', ' ', ' ', '16 ', '13 ', '5 ', '6 ', '8 ', '2 ', '4 ', '148 ', '55 ', '17 ', '8 ', '42 ', '26 ', '50 ', '2 ', '281 ', '120 ', ' ', '6 ', '120432 ', '150000 ', '529 ', ' ', '16 ', '2500 ', '5 ', '68 ', '16 ', '100 ', '216 ', '23 ', '33 ', '140256 ', '19 ', '20 ', '20 ', '49 ', '12 ', '30 ', '5232 ', '20 ', '1 ', ' ', '61 ', '27 ', '53 ', '11 ', '25 ', '0 ', '20 ', '9 ', '3 ', '561 ', '82 ', '13 ', '16 ', '13 ', '28 ', '4 ', ' ', '24 ', '34 ', '8 ', '128 ', '15 ', '513 ', '7 ', '7 ', '5 ', '15 ', '480000 ', '11 ', '54 ', '561 ', '64 ', '6 ', '116 ', '19 ', ' ', '5812 ', '9 ', '32 ', '29 ', '67 ', ' ', '25 ', '6400 ', '10 ', '5 ', '13 ', '98 ', '36 ', '69 ', '2158859 ', '518 ', '15 ', '179 ', ' ', '12 ', '38 ', '65 ', '102 ', '86 ', '7 ', '53 ', '20 ', '1 ', '71 ', '29 ', '20531 ', '65 ', '3 ', '22 ', '38 ', '22 ', '4814 ', '698 ', '13 ', '10 ', '59 ', '56 ', '482 ', '171 ', '5 ', '500 ', '411 ', '8519 ', '21 ', '21 ', '171 ', '7 ', '49 ', '12 ', '3 ', '21 ', '9 ', '8 ', '7 ', '2 ', '11 ', '11 ', '173 ', '5 ', '15 ', '3 ', '105 ', '25000 ', ' ', '18 ', '21000 ', '115 ', '21 ', '206 ', '43680 ', '8 ', '10 ', '59 ', '10 ', '5 ', '5 ', '1000 ', '138 ', ' ', '16 ', '2 ', '10 ', ' ', '8 ', '6 ', '129 ', '81 ', '12 ', '6 ', '22 ', '18 ', '9 ', '754 ', '14 ', '5 ', ' ', ' ', '18 ', '7 ', '7 ', ' ', '7 ', '5 ', '6 ', '4 ', '18 ', '11 ', '25 ', ' ', '20 ', '12 ', '46 ', '9 ', '8 ', '49 ', '11 ', '8 ', '54 ', '36 ', '3916 ', '710 ', '18 ', '8 ', '29 ', '7 ', '9 ', '37 ', '6 ', '1024 ', '1024 ', '14 ', '7 ', '8265 ', '29 ', '25 ', '3 ', '115 ', '1 ', '12 ', '13 ', '200000 ', '6 ', '21 ', '4 ', '2400 ', '175 ', '10 ', '4714 ', '23 ', '17 ', '2 ', '9 ', '8 ', '280 ', '49 ', '3 ', '14 ', '19 ', ' ', '54 ', '8 ', '1087 ', '12 ', '3 ', '17 ', '8 ', '9 ', '12 ', '1656 ', '6 ', '2 ', '11 ', '533 ', '14 ', '84 ', '22 ', '16 ', '52 ', '19 ', '3 ', '14 ', '321 ', '13 ', '13 ', '55 ', '39 ', '4 ', '7 ', '79 ', '1 ', ' ', '14 ', '96 ', '21 ', ' ', '5 ', '2 ', '69 ', '9 ', '124 ', '20 ', '25 ', '11 ', '19 ', '9 ', '9 ', '5 ', '7 ', '4006 ', '2 ', '19 ', '4 ', '13 ', '55 ', '1 ', '7842 ', '15 ', '15 ', '70 ', '7842 ', '4 ', '14 ', '17 ', '23 ', '321 ', '1068 ', '1068 ', '5 ', '6 ', '4 ', ' ', '5 ', '5 ', '15 ', '7 ', '21 ', '9 ', '8 ', '11 ', '21 ', '22 ', '2 ', '241 ', '33 ', '29 ', '7 ', '1 ', ' ', '4 ', '11 ', '47 ', '10 ', '3 ', '2 ', '632 ', '6826 ', '11 ', '525 ', '50 ', '7 ', '16 ', '2 ']

In [116]:
year=[]
year_tag=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')
for i in year_tag[1:]:
    year.append(i.text)
print(len(year)) 
print(year)

622
['1995 ', '1996 ', ' ', '1998 ', '1998 ', '1992 ', '1987 ', '1992 ', '1993 ', '1987 ', '1994 ', '1994 ', ' ', '1988 ', '1992 ', '1995 ', '1995 ', '1990 ', '1997 ', '1996 ', '1988 ', '1989 ', '1994 ', ' ', ' ', '1995 ', ' ', '1992 ', '1987 ', '1997 ', '1998 ', '1995 ', '1998 ', ' ', ' ', '1994 ', ' ', '1989 ', '1996 ', '1990 ', '1990 ', '1987 ', '1999 ', '1989 ', '1988 ', '1988 ', '1989 ', ' ', '1990 ', '1998 ', '1989 ', '1988 ', '1994 ', '1990 ', '1988 ', '1988 ', '1990 ', '1991 ', '1990 ', ' ', '1992 ', '1988 ', '1990 ', '1996 ', '1995 ', '1990 ', ' ', '1992 ', '1992 ', '1994 ', ' ', '1987 ', '1994 ', '1994 ', '1997 ', '1991 ', '1995 ', '1998 ', '1998 ', '1993 ', '1988 ', ' ', ' ', '1992 ', '1993 ', '1988 ', '1989 ', '1988 ', '1987 ', '1993 ', '1988 ', '1999 ', '2001 ', '2001 ', ' ', '1992 ', '1993 ', '1997 ', '1991 ', '1987 ', '1994 ', '1988 ', '1987 ', '1993 ', '1988 ', '1988 ', '1991 ', '1996 ', '1990 ', ' ', '1999 ', '1999 ', '2002 ', ' ', '2000 ', '1999 ', '1999 ', '2001 ', '1999 ', '1999 ', '2000 ', '1999 ', '2000 ', '1999 ', '1999 ', ' ', '1998 ', '1999 ', '2001 ', '1999 ', ' ', '2003 ', '1999 ', '1999 ', '1997 ', '1999 ', '1999 ', '1998 ', ' ', ' ', ' ', '1994 ', ' ', '1993 ', '1990 ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '1989 ', '2006 ', '2006 ', '2007 ', '2007 ', '2007 ', '2007 ', '2008 ', '2008 ', '2008 ', '2007 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2008 ', '2009 ', '2008 ', '2008 ', '2008 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2009 ', '2010 ', '2009 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2010 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2011 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2012 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2013 ', '2014 ', '2013 ', '2013 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2013 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2014 ', '2015 ', '2014 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2014 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2015 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2016 ', '2017 ', '2016 ', '2017 ', '2017 ', '2016 ', '2016 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2016 ', '2016 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2017 ', '2016 ', '2018 ', '2018 ', '2016 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2018 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2018 ', '2018 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2019 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2021 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2020 ', '2021 ', '2021 ']

In [117]:
df=pd.DataFrame({})
df['Name of Data Sets']=name
df['Data Type']=d_type
df['Default Task']=task
df['Attribute Type']=att_type
df['Number of Instances']=instances
df['Number of Attributes']=attributes
df['Year']=year
df

,Name of Data Sets,Data Type,Default Task,Attribute Type,Number of Instances,Number of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

# 9. Scrape the details most watched tv series of all time from imdb.com.

In [118]:
driver =webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [122]:
driver.get('https://www.imdb.com/list/ls095964455/')

In [123]:
Name=[]
Yearspan=[]
Genre=[]
Runtime=[]
Ratings=[]
Votes=[]

In [124]:
location_tags=driver.find_elements_by_xpath("//h3[@class='lister-item-header']")
location_tags[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="11edaeb5-0165-4ff2-866a-84325b34567b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="0f0d5865-4cda-4132-a554-7e4dde578ad4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="2f0fd750-0ed6-4e36-a48f-9590e79b6593")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="9a3fd503-4a8f-4ef5-8d49-fc133580c041")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="1b8f126a-fa47-4cac-a7bd-4aa3fc8ae164")>]

In [125]:
for i in location_tags:
    Name.append(i.text)
Name[0:5]

['1. Game of Thrones (2011–2019)',
 '2. Stranger Things (2016– )',
 '3. The Walking Dead (2010–2022)',
 '4. 13 Reasons Why (2017–2020)',
 '5. The 100 (2014–2020)']

In [126]:
location_tag=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
location_tag[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="585aec69-a4e8-4f8d-baa4-78b46dbc0c89")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="ced62847-ba3c-46b2-a2bf-92e486188d72")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="40df025e-024e-4dfc-9fa5-ead985d31f97")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="4333bbc0-2cd2-4538-9abe-b6a8c6d508fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="f38046f4-0dea-4b28-99ec-ea0166a89a72")>]

In [127]:
for i in location_tag:
    Yearspan.append(i.text)
Yearspan[0:5]

['(2011–2019)', '(2016– )', '(2010–2022)', '(2017–2020)', '(2014–2020)']

In [128]:
location_ta=driver.find_elements_by_xpath("//span[@class='genre']")
location_ta[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="7d913e32-f202-4411-884b-3716f409e019")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="57e7ad74-0873-4904-abc5-26218bb4837c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="7c2dee50-b006-4fae-88d2-863c75c5ec48")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="550bcc55-ffdc-40e6-bbfb-254c211c8f6b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="26078a32-890c-4f03-a1a9-2d7fb19ebb4c")>]

In [129]:
for i in location_ta:
    Genre.append(i.text)
Genre[0:5]

['Action, Adventure, Drama',
 'Drama, Fantasy, Horror',
 'Drama, Horror, Thriller',
 'Drama, Mystery, Thriller',
 'Drama, Mystery, Sci-Fi']

In [130]:
location_t=driver.find_elements_by_xpath("//span[@class='runtime']")
location_t[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="1f1abb68-d3ac-437d-aa65-938097739247")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="dc9e91a2-ddb5-4c85-b85e-ec79125287af")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="3fdcb2d6-334f-4426-844f-3af0dd228693")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="1a46c59a-8644-48a2-89b6-3a7bfca81722")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="323f1363-912c-49e8-9c56-4dc08dcab154")>]

In [131]:
for i in location_t:
    Runtime.append(i.text)
Runtime[0:5]

['57 min', '51 min', '44 min', '60 min', '43 min']

In [132]:
location=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']")
location[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="3174b3d7-4ea0-4329-9661-5d7a28554b17")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="9668fc53-af9e-4fc5-97b8-f22323764bfe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="de4bc01a-7101-48db-a930-dfcb74f5769f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="c6e1c50c-3fbb-42ca-8861-358a1eb5d9a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="82e8548b-956f-48ec-bd1d-1df8f8f8fafc")>]

In [133]:
for i in location:
    Ratings.append(i.text)
Ratings[0:5]

['9.2', '8.7', '8.2', '7.5', '7.6']

In [134]:
locatio=driver.find_elements_by_xpath("//p[@class='text-muted text-small']")
locatio[0:5]

[<selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="2b984c14-b8a3-4f72-963c-bbafd3904583")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="57052a0a-3c9f-48d3-a452-cc76d66884d3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="1c40f718-a025-4a03-bc8a-b703d4035b3d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="36401e52-8a13-4601-9ed2-8daa43e40b17")>,
 <selenium.webdriver.remote.webelement.WebElement (session="15697827f2b846f40136c9e2070f1cbf", element="cab3b3c8-2287-4164-ba70-9c750add589f")>]

In [135]:
for i in locatio:
    Votes.append(i.text)
Votes[0:5]

['18 | 57 min | Action, Adventure, Drama',
 'Stars: Emilia Clarke, Peter Dinklage, Kit Harington, Lena Headey',
 'Votes: 2,021,662',
 '15 | 51 min | Drama, Fantasy, Horror',
 'Stars: Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour']

In [136]:
movies=pd.DataFrame({})
movies['Name']=Name[0:5]
movies['Yearspan']=Yearspan[0:5]
movies['Genre']=Genre[0:5]
movies['Runtime']=Runtime[0:5]
movies['Ratings']=Ratings[0:5]
movies['Votes']=Votes[0:5]
movies

,Name,Yearspan,Genre,Runtime,Ratings,Votes
0,1. Game of Thrones (2011–2019),(2011–2019),"Action, Adventure, Drama",57 min,9.2,"18 | 57 min | Action, Adventure, Drama"
1,2. Stranger Things (2016– ),(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"Stars: Emilia Clarke, Peter Dinklage, Kit Hari..."
2,3. The Walking Dead (2010–2022),(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"Votes: 2,021,662"
3,4. 13 Reasons Why (2017–2020),(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"15 | 51 min | Drama, Fantasy, Horror"
4,5. The 100 (2014–2020),(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"Stars: Millie Bobby Brown, Finn Wolfhard, Wino..."

# 8. Scrape the details of Highest selling novels.Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

In [137]:
driver= webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')
url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)

In [138]:
name=[]
name_tag=driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[2]')
for i in name_tag:
    name.append(i.text)
print(len(name)) 
print(name)

100
['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [139]:
author=[]
author_tag=driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[3]')
for i in name_tag:
    author.append(i.text)
print(len(author)) 
print(author)

100
['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [140]:
sales=[]
sales_tag=driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[4]')
for i in sales_tag:
    sales.append(i.text)
print(len(sales)) 
print(sales)

100
['5,094,805', '4,475,152', '4,200,654', '4,179,479', '3,758,936', '3,583,215', '3,484,047', '3,377,906', '3,193,946', '2,950,264', '2,479,784', '2,315,405', '2,233,570', '2,193,928', '2,183,031', '2,152,737', '2,062,145', '2,052,876', '2,005,598', '1,979,552', '1,928,900', '1,852,919', '1,814,784', '1,787,118', '1,783,535', '1,781,269', '1,743,266', '1,629,119', '1,616,068', '1,583,992', '1,555,135', '1,546,886', '1,539,428', '1,508,205', '1,489,403', '1,352,318', '1,310,207', '1,310,176', '1,231,957', '1,217,712', '1,208,711', '1,204,058', '1,184,967', '1,181,503', '1,181,093', '1,153,181', '1,132,336', '1,130,802', '1,126,337', '1,115,549', '1,108,328', '1,107,379', '1,104,403', '1,092,349', '1,090,847', '1,087,262', '1,054,196', '1,037,160', '1,023,688', '1,015,956', '1,009,873', '1,004,414', '1,003,780', '1,002,314', '998,213', '992,846', '986,753', '986,115', '970,509', '967,466', '963,353', '962,515', '959,496', '956,114', '945,640', '931,312', '925,425', '924,695', '906,968', '905,086', '890,847', '869,671', '869,659', '862,602', '856,540', '845,858', '842,535', '828,215', '820,563', '816,907', '816,585', '815,586', '814,370', '809,641', '808,900', '807,311', '794,201', '792,187', '791,507', '791,095']

In [141]:
publisher=[]
publisher_tag=driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[5]')
for i in publisher_tag:
    publisher.append(i.text)
print(len(publisher)) 
print(publisher)

100
['Transworld', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Random House', 'Bloomsbury', 'Bloomsbury', 'Bloomsbury', 'Transworld', 'Bloomsbury', 'Random House', 'Little, Brown Book', 'Quercus', 'Random House', 'Transworld', 'Little, Brown Book', 'Transworld', 'Little, Brown Book', 'Pan Macmillan', 'Random House', 'Transworld', 'Transworld', 'Quercus', 'Little, Brown Book', 'Penguin', 'Pan Macmillan', 'Penguin', 'Bloomsbury', 'Hodder & Stoughton', 'Bloomsbury', 'Quercus', 'Random House', 'Random House', 'Pan Macmillan', 'Penguin', 'Random House', 'Random House', 'Canongate', 'HarperCollins', 'Orion', 'Pan Macmillan', 'HarperCollins', 'Random House', 'Scholastic Ltd.', 'Orion', 'Bloomsbury', 'Penguin', 'HarperCollins', 'Random House', 'Little, Brown Book', 'Headline', 'HarperCollins', 'Penguin', 'Orion', 'Bloomsbury', 'Random House', 'Random House', 'Scholastic Ltd.', 'Profile Books Group', 'Random House', 'Transworld', 'Random House Childrens Books G', 'Hodder & Stoughton', 'Scholastic Ltd.', 'Random House', 'HarperCollins', 'Random House', 'Penguin', 'Random House', 'HarperCollins', 'Penguin', 'Headline', 'Little, Brown Book', 'HarperCollins', 'Transworld', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Transworld', 'Transworld', 'Random House', 'Headline', 'Random House', 'Transworld', 'Penguin', 'Pan Macmillan', 'Penguin', 'Hodder & Stoughton', 'Transworld', 'D.C. Thomson', 'Penguin', 'Pan Macmillan', 'Transworld', 'Orion', 'Random House', 'Penguin', 'Scholastic Ltd.', 'Orion', 'Penguin']

In [142]:
genre=[]
genre_tag=driver.find_elements_by_xpath('/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr/td[6]')
for i in name_tag:
    genre.append(i.text)
print(len(genre)) 
print(genre)

100
['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [143]:
df=pd.DataFrame({})
df['Book Name']=name
df['Author']=author
df['Volume Sales']=sales
df['Publisher']=publisher
df['Genre']=genre
df

,Book Name,Author,Volume Sales,Publisher,Genre
0,"Da Vinci Code,The","Da Vinci Code,The","5,094,805",Transworld,"Da Vinci Code,The"
1,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows,"4,475,152",Bloomsbury,Harry Potter and the Deathly Hallows
2,Harry Potter and the Philosopher's Stone,Harry Potter and the Philosopher's Stone,"4,200,654",Bloomsbury,Harry Potter and the Philosopher's Stone
3,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix,"4,179,479",Bloomsbury,Harry Potter and the Order of the Phoenix
4,Fifty Shades of Grey,Fifty Shades of Grey,"3,758,936",Random House,Fifty Shades of Grey
...,...,...,...,...,...
95,"Ghost,The","Ghost,The","807,311",Random House,"Ghost,The"
96,Happy Days with the Naked Chef,Happy Days with the Naked Chef,"794,201",Penguin,Happy Days with the Naked Chef
97,"Hunger Games,The:Hunger Games Trilogy","Hunger Games,The:Hunger Games Trilogy","792,187",Scholastic Ltd.,"Hunger Games,The:Hunger Games Trilogy"
98,"Lost Boy,The:A Foster Child's Search for the L...","Lost Boy,The:A Foster Child's Search for the L...","791,507",Orion,"Lost Boy,The:A Foster Child's Search for the L..."
99,Jamie's Ministry of Food:Anyone Can Learn to C...,Jamie's Ministry of Food:Anyone Can Learn to C...,"791,095",Penguin,Jamie's Ministry of Food:Anyone Can Learn to C...

# 3. Scrape the details of selenium exception from guru99.com.

In [155]:
driver = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [156]:
driver.get('https://www.guru99.com/')

In [158]:
driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

In [159]:
Name=[]
Description=[]

In [160]:
dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[1]')
for d in dt:
    Name.append(d.text)

In [161]:
dt = driver.find_elements_by_xpath('//table[@class="table table-striped"]/tbody/tr/td[2]')
for d in dt:
    Description.append(d.text)

In [162]:
import pandas as pd
table=pd.DataFrame({})

table['Name']=Name[1:50]
table['Description']=Description[1:50]

In [163]:
table

,Name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

In [186]:
driver = webdriver.Chrome('/Users/aryanlohan/downloads/chromedriver')

In [187]:
url='https://github.com/'
driver.get(url)
time.sleep(2)

In [188]:
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div[1]/div[2]/nav/ul/li[4]/details/div[1]/ul[1]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [189]:
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

for i in URLs:
    driver.get(i)
    time.sleep(3)
    
    try:
        desc = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        

    try:
        contributor = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')

    try:
        for i in driver.find_elements_by_xpath("//span[@class='color-text-primary text-bold mr-1']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')

Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

Empty DataFrame
Columns: [Repository title, Repository description, Contributors count, Language used]
Index: []